import pygame as pg

SCREEN_SIZE = pg.Vector2(1260, 810)
TARGET_FPS = 144
SCREEN_FLAGS = pg.SCALED | pg.DOUBLEBUF | pg.HWSURFACE | pg.FULLSCREEN
SURFACE_FLAGS = pg.SRCALPHA | pg.HWSURFACE 
APP_NAME = "< Limen >"
MIXER_CHANNEL_COUNT = 32